apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec: 
  containers:
    - name : client
      image: gxwilkerson33/multi-client
      ports:
        - containerPort: 3000